spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
#  jmx:
#    default-domain: jmx-domain

jwt:
  app:
    jwtSecret: dummySecretKey
    jwtExpirationMs: 360000000

server:
  servlet:
    contextPath: /api

logging:
  level:
    com.booster.vocabulary: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
